### ISSUE TITLE
Multi Melter crashes the game

### ISSUE THREAD

**Issue by Glacier7975** [z0mbiesrock/Diamond-Ore#10]
When I put scrap in a multi melter it crashes the game. Crash code:
> NullPointer: 'Attempt to read from field 'mindustry.world.modules.ItemModule mindustry.entities.type.TileEntity.items' on a null object reference'
BlockStorage.acceptItem: 99
BlockStorage.offloadDir: 278
Conveyor.update: 195
TileEntity.update: 324
EntityGroup.update: 51
Logic.update: 241
ApplicationCore.update: 36
ClientLauncher.update: 138
AndroidGraphics.lambda$onDrawFrame$1: 436
-$$Lambda$AndroidGraphics$-UMZ7f6RjD4gjnI5A71J9uqnjKo.run: 2
AndroidGraphics.runProtected: 479
AndroidGraphics.onDrawFrame: 433
GLSurfaceView$GLThread.guardedRun: 1573
GLSurfaceView$GLThread.run: 1272

**Comment by Glacier7975** [comment]
Also it cant be destroyed

**Comment by z0mbiesrock** [comment]
Try redownloading the mod. The script might be corrupted
