### ISSUE TITLE
the latest version doesn't work on android

### ISSUE THREAD

**Issue by ffugio** [z0mbiesrock/Diamond-Ore#19]
The problem comes from the new ships/mechs. Its says about a void something.

**Comment by z0mbiesrock** [comment]
The mod is not mobile-stable, as far as I know. Maybe provide a crash log or screenshot

**Comment by ffugio** [comment]
Here my screen is a bit small. TIA.

**Comment by ChivalricMender** [comment]
Teleportation can't be used

**Comment by ffugio** [comment]
Same problem still occurs even after I cleared the data and reinstalled the game. And I only Loaded the Diamond mod but same problem happens.

**Comment by z0mbiesrock** [comment]
I'm afraid the mod is not compatible with mobile devices since the mod is quite large and it isn't worth it going though endless spaghetti and frustration making it mobile-friendly.
