### ISSUE TITLE
It broke when mixed with other mods

### ISSUE THREAD

**Issue by MIGHTYCLIMBER** [z0mbiesrock/Diamond-Ore#21]
Bruh,this mod only broke when combined with others.can u fix it

**Comment by Cubic-Mc** [comment]
what mod did you play with?

**Comment by MIGHTYCLIMBER** [comment]
> what mod did you play with?

Extended unit arsenal,mechanical warfare,shadow mod,thorge expansion,vanilla upgraded,vanilla enhanced,magnet engine,etc

**Comment by Cubic-Mc** [comment]
there are so many mods you played with,so u can try to play with only one mod at a time and try to see which mod breaks it.:D
