### ISSUE TITLE
Yggdrasil is too op

### ISSUE THREAD

**Issue by Cubic-Mc** [z0mbiesrock/Diamond-Ore#22]
Yggdrasil is too op.It can kill purger easily!!
Apocalypse george is very easy like ground zero with Yggdrasil.
So i request you to Nerf Yggdrasil or add a better boss than purger.(Actually both will be nice :D)

Edit:Please Nerf the fire rate and damage of thorium ammo in Thor!

Everything else is awesome and thank you for making this mod,ill surely contact if any other issue!
Please do the needful.

Thank you in advance!!
Cubic

**Comment by z0mbiesrock** [comment]
> Yggdrasil is too op.It can kill purger easily!!

Its accuracy falters with range, especially against air units.

> Apocalypse george is very easy like ground zero with Yggdrasil.

An overdriven Yggdrasil is that powerful; I actually added more maps which can be harder, as well.

> So i request you to Nerf Yggdrasil or add a better boss than purger.(Actually both will be nice :D)



> Edit:Please Nerf the fire rate and damage of thorium ammo in Thor!

Thorium ammo already has a 0.1x fire rate multiplier _and_ only adds one ammo per item. I could script the thorium missile (i.e. to turn less sharply), but that would require rewriting **all** ammo types, too!

> Everything else is awesome and thank you for making this mod,ill surely contact if any other issue!
> Please do the needful.
> 
> Thank you in advance!!
> Cubic

np; apologies for such a late reply

**Comment by Cubic-Mc** [comment]
ok! thanks a lot!:D
