### ISSUE TITLE
Lambda

### ISSUE THREAD

**Issue by Dinoz-Rule** [z0mbiesrock/Diamond-Ore#23]
i cant figure out how to set where it teleports

**Comment by Cubic-Mc** [comment]
Its possible only on PC
Press Lshift and it will teleport to your mouse pointer

**Comment by z0mbiesrock** [comment]
> i cant figure out how to set where it teleports

Until I am able to figure out how to script ability controls for mobile users, I'm afraid the mod is only fully usable on PC.

> Its possible only on PC
