### ISSUE TITLE
New mech ability

### ISSUE THREAD

**Issue by Cubic-Mc** [z0mbiesrock/Diamond-Ore#24]
Hey hey zombiesrock can u please tell me the ability of that new mech 'Nexus' .I really dont know what does it do?

**Comment by z0mbiesrock** [comment]
Inflicts a damage-over-time debuff onto enemy units within a radius and instantly kill the most powerful units.

**Comment by Cubic-Mc** [comment]
does it do the same on blocks,guns,walls,etc?
