### ISSUE TITLE
Bug/Error

### ISSUE THREAD

**Issue by UserNotNeeded** [z0mbiesrock/Diamond-Ore#25]
1.
File: dark-sporepress.hjson
[EcmaError] ReferenceError: "func" is not defined. (spore-blocks#530
2.
File: water-decorruptor.hjson
[EcmaError] ReferenceError: "func" is not defined. (water-decorruptor#16)
![Screenshot_2020-09-15-11-14-55-636_io anuke mindustry](https://user-images.githubusercontent.com/71320104/93193559-4c1e1500-f747-11ea-81d3-ca968213e97f.jpg)
![Screenshot_2020-09-15-11-14-51-655_io anuke mindustry](https://user-images.githubusercontent.com/71320104/93193571-50e2c900-f747-11ea-9f21-4fee3d28d31c.jpg)

**Comment by UserNotNeeded** [comment]
Forgot to mention: I play on mobile

**Comment by Cubic-Mc** [comment]
zombiesr0ck did say that this mod is highly stable only for pc.
But i have tried the older versions and they work fine on mobile.
