### ISSUE TITLE
sporeveyor is ded

### ISSUE THREAD

**Issue by gh-doot** [z0mbiesrock/Diamond-Ore#30]
![image](https://user-images.githubusercontent.com/48828036/100754460-90df5100-3404-11eb-9b68-6cd8d36a4a7b.png)

**Comment by Rickyling97** [comment]
Can confirm, placing a spore conveyor belt caused the game to crash and print out the same error mentioned above. That specific sector will crash every time I try to re-enter it.

**Comment by z0mbiesrock** [comment]
already fixed
