### ISSUE TITLE
Problems adding to a server

### ISSUE THREAD

**Issue by juandi9585** [z0mbiesrock/Diamond-Ore#37]
A friend and I are dying to play this mod on a server. However, whenever I add any version of it, the server's command center will fail to load it and close up. Are we using the wrong file for the mod? Or is it not compatible for servers? Everything else is up to date.
I'm sorry if this is not the place for this kind of questions  but I didn't find anywhere else to do so

**Comment by z0mbiesrock** [comment]
> Are we using the wrong file for the mod?

yeah

**Comment by juandi9585** [comment]
so which one is it? because I've been trying to use the 6.0 branch and the server terminal just goes crazy and closes
