### ISSUE TITLE
Hey you ok you are not updating your mod anymore

### ISSUE THREAD

**Issue by alpha-gamer-pro** [z0mbiesrock/Diamond-Ore#41]
Um dev pls update this mod further.

**Comment by DraskyWatcher** [comment]
agree

**Comment by d689** [comment]
also mod broke in v7,the green spooder tree and the purger broke.diamond ore mod units are now not buildable

**Comment by d689** [comment]
plus some broken blocks,the author really need patching the mods

**Comment by z0mbiesrock** [comment]
I'm sorry, but @Anuken made it impossible for me to reliably update the mod to V7.

**Comment by Anuken** [comment]
How?

**Comment by z0mbiesrock** [comment]
So until V7 comes out, I'm afraid you'll have to wait a bit longer, so I can update it correctly
