### ISSUE TITLE
All of a sudden I can't use your mod due to version restrictions

### ISSUE THREAD

**Issue by DatOnePlayer** [z0mbiesrock/Diamond-Ore#8]
Umm why?

**Comment by ghost** [comment]
Same here. It says requires version 104.10, but the latest release is 104.6

**Comment by z0mbiesrock** [comment]
Latest release IS 14.10.
Update your game

**Comment by ghost** [comment]
> Latest release IS 14.10.
> Update your game

From the Mindustry Github, the latest release is 104.6. https://github.com/Anuken/Mindustry/releases

Your mod requires v10 (ten), not v1 (one)

**Comment by z0mbiesrock** [comment]
> From the Mindustry Github, the latest release is 104.6. https://github.com/Anuken/Mindustry/releases
> 
> Your mod requires v10 (ten), not v1 (one)

According to Steam the latest released build is 104.10

**Comment by ghost** [comment]
> > From the Mindustry Github, the latest release is 104.6. https://github.com/Anuken/Mindustry/releases
> > Your mod requires v10 (ten), not v1 (one)
> 
> According to Steam the latest released build is 104.10

Ok. I'm on Android which is probably why it isn't at v10 yet. Thanks! Happy Easter!

**Comment by kapzduke** [comment]
> > > From the Mindustry Github, the latest release is 104.6. https://github.com/Anuken/Mindustry/releases
> > > Your mod requires v10 (ten), not v1 (one)
> > 
> > 
> > According to Steam the latest released build is 104.10
> 
> Ok. I'm on Android which is probably why it isn't at v10 yet. Thanks! Happy Easter!

you can literally download it from itch.io
